<?php /** @var \Training\DependencyExample\Block\Example $block */?>

<div>
    <h2>Dependency Example</h2>
</div>

<p>
    Class Main id is: <?= $block->getMain()->getId()?>
</p>

<p>
    CLass Injectable id is: <?= $block->getMain()->getInjectable()->getId()?>
</p>

<p>
    CLass NonInjectable id is: <?= $block->getMain()->getNonInjectable()->getId()?>
</p>

<p>
    CLass Util name is: <?= $block->getMain()->getUtil()->getName()?>
</p>